platform :ios, '8.0'
use_frameworks!
target 'qingsongshi' do
  pod 'PLPlayerKit', :path => '../PLPlayerKit'
  pod 'HappyDNS', :path => '../HappyDNS'
  
  pod 'Socket.IO-Client-Swift', :path => '../Socket.IO-Client-Swift'
end
